### ISSUE TITLE
Typography and shadow dom

### ISSUE THREAD

**Issue by daKmoR** [castastrophe/wc-theming-standards#1]
I'm curious about the Typography part - font-size, line-height, ... pierce the shadow-dom.

so how would you use `--wc-theme--FontSize`?

**Comment by castastrophe** [comment]
Thanks for posting this here for discussion! Despite the fact that they may pierce the Shadow DOM, the main goal of theming is to define a set of standards for a website. These variables can be used in web components and vanilla html as a means of synchronizing the look-and-feel. Defining the typography hierarchy is an important part of this visual language. That's why I proposed including them in the set of theming variables.

That said, this standard is largely around naming conventions so it would be optional as to if you want to include them in your theme. Web components using the theme would have fallbacks so it wouldn't hurt anything to leave them out.

**Comment by castastrophe** [comment]
To clarify here too, the proposal for [typography](https://github.com/castastrophe/wc-theming-standards/wiki/Proposed-variables#typography) includes definitions for default (p tags and general content on the site) as well as hierarchical levels (h-tags for example).

This means you could end up with a set of definitions that look like this:

```css
:root {
  --theme--FontSize: 14px;
  --theme--FontSize--alpha: 16px;
  --theme--FontSize--beta: 18px;
  --theme--FontSize--gamma: 22px;
  --theme--FontSize--delta: 24px;
  --theme--FontSize--epsilon: 26px;
  --theme--FontSize--zeta: 28px;
}
```

Then in your codebase, if you wanted to set the font-size and just let it cascade into your web component, you could do this:

```css
body {
    font-size: var(--theme--FontSize, 12px);
}
```

But it lets the web component opt out of that default and instead select a particular sizing:

```css
:slotted(h2) {
    font-size: var(--theme--FontSize--beta, 20px);
}
```
